### ISSUE TITLE
imgproxy stops downloading source images randomly

### ISSUE THREAD

**Issue by renchap** [imgproxy/imgproxy#1014] opened 2022-10-19 16:33 UTC
We are encountering a weird issue with our production `imgproxy` deployment.

It is deployed on Google Cloud Run (managed container platform) and has been running fine for quite some time. Thanks a lot for this btw 👍 

Our setup is processing about 200k requests per day without any issues, but lately some containers began stop processing images and get stuck until we kill them.

We see logs like this when it happens:

```
time="2022-10-19T09:48:50Z" level="error" message="Completed in 24.949903028s /insecure/resize:fill:1500:0/plain/gs:%2F%2Fxxx/product/535a49ee_default.jpeg" request_id="DJJBxB3d3ld7xUV-B1hbp" method="GET" status="500" client_ip="xxx" error="Can't download source image: The image request timed out"
time="2022-10-19T09:48:50Z" level="error" message="Completed in 10.000268855s /insecure/resize:fill-down:120:120/plain/gs:%2F%2Fxxx/prod/a2e02af8455e435b8dcca2d67/acf8e1b8183e4f5e9498d1905_default.jpeg" request_id="Nj3ey4iGeLI_yAq1vOQuk" method="GET" status="503" client_ip="xxx" error="Request was timed out after 10.000235681s"
```

Nothing changes on the configuration side when this issue happen, and the other `imgproxy` containers seems to be working fine.
The only way to solve the issue is to deploy a new Cloud Run revision, which stops the existing containers (including the stuck one) and launches new ones.

We do not have health checks setup yet as they are a new Cloud Run feature and not supported by Terraform, but we plan to add them manually at some point to see if it detects the stuck containers (but as they still report timeouts, I dont think it will work).

We tried various Cloud Run settings (reducing concurrency…) without any effect, it keeps reproducing about once a day.

Do you have any ideas on what could be causing this, and how we could troubleshoot this further?

We are currently running imgproxy 3.7.2 and plan to upgrade tomorrow to see how it goes, but this issue did not appear after our previous upgrade, but some time after.

**Comment by renchap** [comment] 2022-10-19 21:09
This in interesting, we are using the "on demand" mode, so our containers are heavily throttled when no requests are in-flight. We will try to set them to "always-on" and see if it still occurs.

**Comment by DarthSim** [comment] 2022-10-20 09:39
> We will try to set them to "always-on" and see if it still occurs.

That's what I was going to offer. Please keep me informed if switching to "always-on" helps or not.

**Comment by renchap** [comment] 2022-10-20 09:51
We switched to "always-on" 12 hours ago, and the issue happened again a few minutes ago :(

We are now trying to switch to the Cloud Run "second generation" environment, which uses full VMs (compared to the 1st generation which used [`gvisor`](https://gvisor.dev)). We will keep you updated with the results, but are running out of ideas on what could cause the issues.

On our list currently:
- upgrading to 3.9.0
- downgrading to an earlier v3 version (but which one?)
- switching from `gs://` source URLs to plain `https://storage.googleapis.com/…` urls

**Comment by Klaitos** [comment] 2022-10-20 11:35
Hello, I'm working with renchap on this issue.
Maybe this stack trace can help you to debug with us : 

```
*ierrors.Error Can't download source image: The image request timed out 
    /app/errorreport/errorreport.go:20 Report
    /app/server.go:144 withPanicHandler.func1.1
    runtime/panic.go:884 gopanic
    /app/processing_handler.go:307 handleProcessing
    /app/server.go:112 withCORS.func1
    /app/server.go:159 withPanicHandler.func1
    /app/router/router.go:101 (*Router).ServeHTTP
    net/http/server.go:2947 serverHandler.ServeHTTP
    net/http/server.go:1991 (*conn).serve
```

As already describe, the source image come from GCS buckets so i don't think the issue is from the source image.

**Comment by MikeVL** [comment] 2022-10-21 07:07
I have same issue with loading source from URLs

```
ERROR   [2022-10-21T07:06:05Z] Completed in 10.000386154s /url/RYopK7X6M0wtFNcEbOpNzWFtZSrwYGgO0r3fa741zbI/rs:fit:150:150/g:sm/aHR0cHM6Ly93d3cu/ZXRhbG9ucHJpYm9y/LnJ1Ly91cGxvYWQv/aWJsb2NrL2Q2Yy9k/NmNkMjZlYmMxY2Iw/NDE3ZjVlMGYwZDEw/MjYxNTViYy5qcGc  request_id=eNDAXKI_GB5Nu_DBpKyIG method=GET status=503 client_ip=66.249.64.158 error="Request was timed out after 10.000370522s"
ERROR   [2022-10-21T07:06:05Z] Completed in 10.001073413s /url/EFQgTOpYlDN_nKi8VFg7lM9nuzmbuHGfPaMag1i2nR4/rs:fit:150:150/g:sm/aHR0cHM6Ly90ZXNs/aS5jb20vdXBsb2Fk/L2libG9jay82NGIv/MmEzM2M5MmJfZWY5/NF8xMWRkX2FkMGRf/MDAzMDQ4ODViN2U3/LmpwZw  request_id=VJf3fHXMvQanWxTCbkDNd method=GET status=503 client_ip=66.249.64.133 error="Request was timed out after 10.001055063s"
ERROR   [2022-10-21T07:06:05Z] Completed in 10.000792364s /url/7wOVNXZwKJcLK5QhBmDaVNufvQcwGLpLQePrmfpis8A/rs:fit:1200:900/g:sm/aHR0cHM6Ly8yMjBj/aXR5LnJ1L3VwbG9h/ZC9NYWluX2ltYWdl/cy84MmY4MzhmZC0z/YmYwLTExZWMtODMx/MS0wMDUwNTZiZGQx/OTMuanBlZw  request_id=BtFAJo8H4rT-Z1GjdoMPm method=GET status=503 client_ip=66.249.64.158 error="Request was timed out after 10.000753133s"
INFO    [2022-10-21T07:06:06Z] Started /url/irpM0djI675xpM9WktzYl3JIMGj6u4cPDeF-DVUzhHI/rs:fit:1200:900/g:sm/aHR0cHM6Ly8yMjBj/aXR5LnJ1L3VwbG9h/ZC9NYWluX2ltYWdl/cy9jOGExMWE3MC04/MDkzLTExZWMtOGU3/My0wMDUwNTZiZGQx/OTMuanBlZw  request_id=HywObryKFIRKl6mj4cHD1 method=GET client_ip=66.249.64.158
ERROR   [2022-10-21T07:06:06Z] Completed in 10.000375936s /url/HCQGUq38ILp13inufivs-YhhV1OdGw9BXpCeBRKie-g/rs:fill:54:54/el:1/g:ce/aHR0cHM6Ly93d3cu/Z3JhdmF0YXIuY29t/L2F2YXRhci9lNzQ0/Y2RmOTE4ZTVjNDJl/MWMwMTIyYTQxMmY1/ZTQ1ZD9zPTU0JmQ9/aWRlbnRpY29u  request_id=RxUlqWw0ecqToceDBzqYc method=GET status=503 client_ip=89.151.155.44 error="Request was timed out after 10.000340538s"
INFO    [2022-10-21T07:06:06Z] Started /url/HCQGUq38ILp13inufivs-YhhV1OdGw9BXpCeBRKie-g/rs:fill:54:54/el:1/g:ce/aHR0cHM6Ly93d3cu/Z3JhdmF0YXIuY29t/L2F2YXRhci9lNzQ0/Y2RmOTE4ZTVjNDJl/MWMwMTIyYTQxMmY1/ZTQ1ZD9zPTU0JmQ9/aWRlbnRpY29u  request_id=a5rYm_ez0mabPw-CWzsn_ method=GET client_ip=89.151.155.44
ERROR   [2022-10-21T07:06:06Z] Completed in 10.001079872s /url/zaBYNz076x5_G-yE3eacnQxHQmsv2v9j9VX5VTwZFfs/rs:fit:600:400/g:sm/aHR0cHM6Ly9wbWt0/LnJ1L2ltYWdlL2Nh/Y2hlL2NhdGFsb2cv/Nzc0NF9hMTE4MWU4/My0wNjUxLTExZWMt/OGVkMi0wMDI1MjJi/NDFjYTIuLTEwMHgx/MDAucG5n  request_id=HFNWRoutT4B3Hn7VwhCbk method=GET status=503 client_ip=66.249.64.158 error="Request was timed out after 10.001063729s"
INFO    [2022-10-21T07:06:06Z] Started /url/zaBYNz076x5_G-yE3eacnQxHQmsv2v9j9VX5VTwZFfs/rs:fit:600:400/g:sm/aHR0cHM6Ly9wbWt0/LnJ1L2ltYWdlL2Nh/Y2hlL2NhdGFsb2cv/Nzc0NF9hMTE4MWU4/My0wNjUxLTExZWMt/OGVkMi0wMDI1MjJi/NDFjYTIuLTEwMHgx/MDAucG5n  request_id=ukR19nHSQptXB6HOS8DNd method=GET client_ip=66.249.64.158
ERROR   [2022-10-21T07:06:06Z] Completed in 10.000668629s /url/x9397YoTodkVHhvITBemmfi5jsEJlsiwo4xzbI77zko/rs:fit:150:150/g:sm/aHR0cHM6Ly9zaG9w/MjIwLnJ1L2ltYWdl/cy9kYXRhL2NhdC8y/ODg0NDhfYmlnXzE2/NDA3Njc2MjMuanBn  request_id=_4eVi_OqoqK3HvsfOTzhE method=GET status=503 client_ip=66.249.64.158 error="Request was timed out after 10.000655043s"
INFO    [2022-10-21T07:06:06Z] Started /url/h72CQK4DHJ26JoeTq4xtRlk-Qn9m8nx51EnZIRNVGJc/rs:fit:1200:900/g:sm/aHR0cHM6Ly9ncmFk/aWVudGVjaC5ydS9z/dG9yYWdlLzc3YS8x/ZDUvZTNjLzc3YTFk/NWUzYzRkYzRmNTg5/YjA5NjA2MDU0OWNm/NmVmLmpwZWc  request_id=uKoGUYPhPM4GaP7Yrx9lc method=GET client_ip=66.249.64.158
ERROR   [2022-10-21T07:06:06Z] Completed in 10.000254503s /url/h72CQK4DHJ26JoeTq4xtRlk-Qn9m8nx51EnZIRNVGJc/rs:fit:1200:900/g:sm/aHR0cHM6Ly9ncmFk/aWVudGVjaC5ydS9z/dG9yYWdlLzc3YS8x/ZDUvZTNjLzc3YTFk/NWUzYzRkYzRmNTg5/YjA5NjA2MDU0OWNm/NmVmLmpwZWc  request_id=v6sEfHNhH9zzdSEBbHMri method=GET status=503 client_ip=66.249.64.158 error="Request was timed out after 10.000240869s"
ERROR   [2022-10-21T07:06:06Z] Completed in 10.000405163s /url/7dCz9oopxTcrDvmIcYspTWy4rfiFV-sVzozx_53NT9c/rs:fit:150:150/g:sm/aHR0cHM6Ly9sZWRy/dXMub3JnL3VwbG9h/ZC9pYmxvY2svZGEx/L2RhMWEwZGQyODcz/ZGUwYzkzZWJkN2Ux/Y2M5NmZjNmRhLmpw/Zw  request_id=SHFUYLtsUuPd7oqA8-Ts8 method=GET status=503 client_ip=66.249.64.158 error="Request was timed out after 10.000372955s"
INFO    [2022-10-21T07:06:06Z] Started /url/7dCz9oopxTcrDvmIcYspTWy4rfiFV-sVzozx_53NT9c/rs:fit:150:150/g:sm/aHR0cHM6Ly9sZWRy/dXMub3JnL3VwbG9h/ZC9pYmxvY2svZGEx/L2RhMWEwZGQyODcz/ZGUwYzkzZWJkN2Ux/Y2M5NmZjNmRhLmpw/Zw  request_id=NHh0j203qIPsBgDz4vTaQ method=GET client_ip=66.249.64.158
INFO    [2022-10-21T07:06:06Z] Started /url/8wg3tzD78a6umGgUaO3wVjCs9IduERC10bi6J-oQfco/rs:fit:1200:900/g:sm/aHR0cHM6Ly9zaG9w/MjIwLnJ1L2NvbnN0/cnVjdG9yL2ltYWdl/cy9naXJhL0NsYXNz/aVgvYmlnL2Rldmlj/ZXMvMXhfU3ZldG9y/ZWdfQW50cmFjaXRf/R2lyYS5wbmc  request_id=IoJz6Eiaksh7EBxYV0gYX method=GET client_ip=66.249.64.158
ERROR   [2022-10-21T07:06:07Z] Completed in 10.000445157s /url/8wg3tzD78a6umGgUaO3wVjCs9IduERC10bi6J-oQfco/rs:fit:1200:900/g:sm/aHR0cHM6Ly9zaG9w/MjIwLnJ1L2NvbnN0/cnVjdG9yL2ltYWdl/cy9naXJhL0NsYXNz/aVgvYmlnL2Rldmlj/ZXMvMXhfU3ZldG9y/ZWdfQW50cmFjaXRf/R2lyYS5wbmc  request_id=P0jgUxTkAsUku-NoloqAg method=GET status=503 client_ip=66.249.64.158 error="Request was timed out after 10.000423741s"
ERROR   [2022-10-21T07:06:07Z] Completed in 10.000311458s /url/z-CpuJuPgZuC6JdjuhWFTGVNkMOH1maF0AmIp15t5M4/rs:fit:150:150/g:sm/aHR0cHM6Ly9sZWRw/cmVtaXVtLnJ1L3Vw/bG9hZC9pYmxvY2sv/ZGYxL3N2ZXRvZGlv/ZG55eV9zdmV0aWxu/aWtfMzBfcHJfb3Bf/MzBfdmF0dF9pcDY1/Xzg5N19tbV9vcGFs/LmpwZw  request_id=OqWxBlmrOXoJuIb8VAkAu method=GET status=503 client_ip=66.249.64.158 error="Request was timed out after 10.000286238s"
ERROR   [2022-10-21T07:06:07Z] Completed in 10.000179747s /url/8wg3tzD78a6umGgUaO3wVjCs9IduERC10bi6J-oQfco/rs:fit:1200:900/g:sm/aHR0cHM6Ly9zaG9w/MjIwLnJ1L2NvbnN0/cnVjdG9yL2ltYWdl/cy9naXJhL0NsYXNz/aVgvYmlnL2Rldmlj/ZXMvMXhfU3ZldG9y/ZWdfQW50cmFjaXRf/R2lyYS5wbmc  request_id=ykGwpO_y2vcxvz1ZMbh2D method=GET status=503 client_ip=66.249.64.158 error="Request was timed out after 10.000148708s"
INFO    [2022-10-21T07:06:07Z] Started /url/8wg3tzD78a6umGgUaO3wVjCs9IduERC10bi6J-oQfco/rs:fit:1200:900/g:sm/aHR0cHM6Ly9zaG9w/MjIwLnJ1L2NvbnN0/cnVjdG9yL2ltYWdl/cy9naXJhL0NsYXNz/aVgvYmlnL2Rldmlj/ZXMvMXhfU3ZldG9y/ZWdfQW50cmFjaXRf/R2lyYS5wbmc  request_id=Vomj2dhGbtItp-zmNXhWA method=GET client_ip=66.249.64.158
INFO    [2022-10-21T07:06:07Z] Started /url/z-CpuJuPgZuC6JdjuhWFTGVNkMOH1maF0AmIp15t5M4/rs:fit:150:150/g:sm/aHR0cHM6Ly9sZWRw/cmVtaXVtLnJ1L3Vw/bG9hZC9pYmxvY2sv/ZGYxL3N2ZXRvZGlv/ZG55eV9zdmV0aWxu/aWtfMzBfcHJfb3Bf/MzBfdmF0dF9pcDY1/Xzg5N19tbV9vcGFs/LmpwZw  request_id=LNT35AWFJBprPZHlGhcBj method=GET client_ip=66.249.64.158
INFO    [2022-10-21T07:06:07Z] Started /url/4Lm6iO4HGoOAzrROsD8K69MplzcP4qV-Vitt19JdrZE/rs:fit:1200:900/g:sm/aHR0cHM6Ly9yczI0/LnJ1L2N0bGcvZWRp/L0lFSy9CUi9CUi1S/MTEtMTYtSzQ3L0JS/LVIxMS0xNi1LNDdf/MS5qcGVn  request_id=2_8FjTBznIUEURmmCzaIG method=GET client_ip=178.35.187.246
ERROR   [2022-10-21T07:06:07Z] Completed in 10.002432568s /url/VVXNYG1EhXkBWEg-NdXZJzAGyUo3jTwUiwGeTRnApXQ/rs:fit:150:150/g:sm/aHR0cHM6Ly90bWVs/ZWN0cm9uaWNzLnJ1/Ly9pbWcvcHJvZHVj/dHMvb3JpZy9jZThk/YzgzMmMuY2xvdWRp/bWcuaW8vdjcvX2Nk/bl8vRjAvNTUvRDAv/MDAvMC84NzM3NDNf/MS5qcGc  request_id=29wQFZmbH8RJhgnDG8IZ4 method=GET status=503 client_ip=66.249.64.158 error="Request was timed out after 10.002318266s"
ERROR   [2022-10-21T07:06:07Z] Completed in 10.000459835s /url/eqf1TfhT51hD5tC6FZN27-46aeiwuLpsShSRdrm5qCY/rs:fit:600:400/g:sm/aHR0cHM6Ly93d3cu/ZWxlY3Ryb2R1cy5y/dS91cGxvYWQvaWJs/b2NrL2Y5Ni9mOTYx/MmMzMzRiYjlkYjlh/YjRlMGEzOGE3ZjM3/ZWY1My5qcGc  request_id=0kpdDCy7nDr5uVWNcvIsC method=GET status=503 client_ip=66.249.69.116 error="Request was timed out after 10.000421188s"
ERROR   [2022-10-21T07:06:07Z] Completed in 10.000962267s /url/taS2ggw7BZZGzqhXA230oc8A-lYGnHSnpzhLNjrdJ_s/rs:fit:1200:900/g:sm/aHR0cHM6Ly8yMjBj/aXR5LnJ1L3VwbG9h/ZC9NYWluX2ltYWdl/cy8wMzIxNjA1MC03/OTI2LTExZWItODI1/Ny0wMDUwNTZiZGQx/OTMuanBlZw  request_id=y4-1hdMUR68rFYrCapmLE method=GET status=503 client_ip=66.249.64.158 error="Request was timed out after 10.000930722s"
INFO    [2022-10-21T07:06:07Z] Started /url/oYWRYdqRC-wBGrDW9cPqIg_mRhtpo2RFlqjpBZtALOI/rs:fit:150:150/g:sm/aHR0cHM6Ly9tZWRp/YS5ycy1vbmxpbmUu/Y29tL3RfbGFyZ2Uv/UjYxMTMzMzItMDEu/anBn  request_id=X04jDBg5IqPvssx_0t9jj method=GET client_ip=66.249.64.158
ERROR   [2022-10-21T07:06:08Z] Completed in 10.000826792s /url/eqf1TfhT51hD5tC6FZN27-46aeiwuLpsShSRdrm5qCY/rs:fit:600:400/g:sm/aHR0cHM6Ly93d3cu/ZWxlY3Ryb2R1cy5y/dS91cGxvYWQvaWJs/b2NrL2Y5Ni9mOTYx/MmMzMzRiYjlkYjlh/YjRlMGEzOGE3ZjM3/ZWY1My5qcGc  request_id=eXNvIfkACaYaZviV9Q1FU method=GET status=503 client_ip=66.249.69.116 error="Request was timed out after 10.000809456s"
ERROR   [2022-10-21T07:06:08Z] Completed in 10.000475092s /url/TTlAvyHk_N0Xf8PCUmRni0H15gFlCSbAQRSfzMIbTMU/rs:fit:1200:900/g:sm/aHR0cHM6Ly9ob25l/eXZlbGwuZW5lcmd5/L3dhLWRhdGEvcHVi/bGljL3Nob3AvcHJv/ZHVjdHMvMzkvNDQv/NTQ0MzkvaW1hZ2Vz/LzUyODk0L1ZBUy45/NzAuanBn  request_id=TExuY8vpUkB0Uku1ZNElW method=GET status=503 client_ip=66.249.64.158 error="Request was timed out after 10.000442491s"
INFO    [2022-10-21T07:06:08Z] Started /url/eqf1TfhT51hD5tC6FZN27-46aeiwuLpsShSRdrm5qCY/rs:fit:600:400/g:sm/aHR0cHM6Ly93d3cu/ZWxlY3Ryb2R1cy5y/dS91cGxvYWQvaWJs/b2NrL2Y5Ni9mOTYx/MmMzMzRiYjlkYjlh/YjRlMGEzOGE3ZjM3/ZWY1My5qcGc  request_id=Wp7N73glHcUJZOmtaZ1nU method=GET client_ip=66.249.69.116
ERROR   [2022-10-21T07:06:08Z] Completed in 10.000719307s /url/45t_-QvNdy1T9PTtCfFCXQdbDwAP7IzHOIty_AMaT3I/rs:fit:600:400/g:sm/aHR0cHM6Ly9nay1h/YnNvbHV0MS5ydS91/cGxvYWQvaWJsb2Nr/L2Y2My8xMjE1NzMy/MTIxNTczMkM0UEVB/MDYwMTBBMDAxMzAw/U3ZldG92eWV6YXZl/c3liZXpvcGFzbm9z/dGkuanBn  request_id=MN8Rc9uS3_Gwd2pkA1xVw method=GET status=503 client_ip=66.249.64.158 error="Request was timed out after 10.000704055s"
INFO    [2022-10-21T07:06:08Z] Started /url/eXjIwRyvjomQ3Q6L_8dAIGrOXBpe6OlDQEDed6ZXukE/rs:fit:150:150/g:sm/aHR0cHM6Ly9ya20t/ZWxlY3Ryby5ydS91/cGxvYWQvaWJsb2Nr/LzBiZS8wYmU3MzJl/ZGU2NTkxYmY4ZjAy/ZDM2NjAyZTQzMDE3/YS5qcGc  request_id=237F7we2YJWvXMQbyj6pL method=GET client_ip=66.249.64.158
INFO    [2022-10-21T07:06:08Z] Started /url/oYWRYdqRC-wBGrDW9cPqIg_mRhtpo2RFlqjpBZtALOI/rs:fit:150:150/g:sm/aHR0cHM6Ly9tZWRp/YS5ycy1vbmxpbmUu/Y29tL3RfbGFyZ2Uv/UjYxMTMzMzItMDEu/anBn  request_id=7a_0l6-lkx0_gGo30TCIP method=GET client_ip=66.249.64.158
ERROR   [2022-10-21T07:06:08Z] Completed in 10.000193696s /url/oYWRYdqRC-wBGrDW9cPqIg_mRhtpo2RFlqjpBZtALOI/rs:fit:150:150/g:sm/aHR0cHM6Ly9tZWRp/YS5ycy1vbmxpbmUu/Y29tL3RfbGFyZ2Uv/UjYxMTMzMzItMDEu/anBn  request_id=gvd7IbinfxfSmM0pKQnPK method=GET status=503 client_ip=66.249.64.158 error="Request was timed out after 10.000148358s"
```

**Comment by renchap** [comment] 2022-10-21 11:04
@MikeVL is this with CloudRun as well?

**Comment by DarthSim** [comment] 2022-10-21 12:01
@renchap @Klaitos imgproxy's GCS transport hasn't been changed in ages, so downgrading imgproxy won't help. imgproxy uses the GCS client provided by the official SDK, so there are not many things we can tune :(

Switching to the 2nd generation environment may help as they promise better networking. Not sure if the networking is the cause but I'd try.

Switching to plain `https://storage.googleapis.com/…` URLs may also help as requests to them are served by the HTTP client configured by imgproxy.


@MikeVL Your issue seems to be completely different. I'd recommend configuring a metrics collection to see what's going wrong.

**Comment by DarthSim** [comment] 2022-11-07 11:20
@renchap @Klaitos Do you have any updates?

**Comment by renchap** [comment] 2022-11-07 11:33
> @renchap @Klaitos Do you have any updates?

We are running on the latest commit and it still happens. We implemented a liveness probe so the containers are restarted automatically but we still dont know the cause.

We plugged imgproxy into our Sentry account and are getting timeout errors when this happens, but nothing really useful.

I plan to deploy a change today to use plain https urls as source and see if it has any impact.

**Comment by DarthSim** [comment] 2022-11-07 11:49
Could you try `v3.10.0`?

BTW, is the issue with malformed images solved with the latest build? I hoped it was the cause.

**Comment by DarthSim** [comment] 2022-11-07 12:50
Do you collect any traces? Datadog, New Relic, OpenTelemetry? It'd be interesting to take a look at the traces of the requests that are close to timeout.

**Comment by renchap** [comment] 2022-11-07 13:08
We tried to configure Datadog with a trial account for this.

When the problem starts, a 3.85s request:
<img width="959" alt="image" src="https://user-images.githubusercontent.com/42070/200316740-2bb7ffe8-da0a-441f-9647-53d5367d2ff0.png">
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/42070/200316817-976382ca-ee09-42c8-a7ac-35aded49be60.png">


Then 6.83s, ended up with a `Can't download source image: The image request timed out` error
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/42070/200317051-2348d108-e66e-44d2-9e59-51106d2216cf.png">
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/42070/200317091-0c259451-ae71-43a3-a027-5911da536b21.png">

And now all queries end up with a 10s `queue` span and never finish:
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/42070/200317248-53d906ed-8381-4e73-9815-bf846d0a2348.png">
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/42070/200317294-96fb11b2-6001-4c52-8e97-2f24a41bfccb.png">

In Sentry, we have timeout errors like this one, and those are the only errors reported by imgproxy:
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/42070/200317662-e1e4bd07-8d44-4455-90a5-d3acfa67fa51.png">

We can share more details over a screensharing session if you want more info (but I dont think there is a lot more available in what we collected at the moment).

If you think it might help and provide more useful data, we can also configure OpenTracing to send the traces to either Google Cloud Trace or Honeycomb.

**Comment by Klaitos** [comment] 2022-11-09 13:16
I will send it you on the last email thread we had together with renchap. I'm not sure this is the root cause because when i re-call the same image everything works well :(

**Comment by DarthSim** [comment] 2022-11-09 13:31
I highly doubt the picture is a root cause, too, yet it won't harm anyone if I check it. I'm just out of any ideas about what goes wrong here. My first idea was that imgproxy doesn't close connections properly. But in this case, we wouldn't have a situation where downloading gradually slows down. And the last screenshot shows that imgproxy is getting the responses from GCS, it is just unable to read their bodies in time.

Could you also share your setup details? Especially, the number of CPUs, maximum requests per container, and configured IMGPROXY_CONCURRENCY.

**Comment by DarthSim** [comment] 2022-11-09 13:37
Yeah, as I expected, the pictures you sent cause no issue. So this is a networking issue I guess :(

**Comment by Klaitos** [comment] 2022-11-09 13:47
We allow a Cloud Run concurrency of 60 requests simultaneous with 2 cpu.
imgproxy is configured with : IMGPROXY_MAX_CLIENTS = 80 and IMGPROXY_CONCURRENCY is not set.
Both of the cloud run and bucket are in same region yes.

I was also wondering it if was an issue with max client connections to the bucket.

**Comment by DarthSim** [comment] 2022-11-09 14:15
I'd try to explicitly set `IMGPROXY_CONCURRENCY=4`. It looks like imgproxy successfully detects CPUs number on GCR, but damn, I'd try anything at this point :(

**Comment by shakalandy** [comment] 2023-03-18 08:29
Having a similar issue over here.
Imgproxy stops working after several timeouts

```
ERROR   [2023-03-18T08:24:56Z] Completed in 5.076879661s /Kc1dSoUDos202QHn-kUH2zSfVWBicc3GGfAoxLQot18/rs:fit:0:1200/g:sm/aHR0cHM6Ly9hcGkua3J1dS5jb20vdX.... request_id=zrP8vNByraNgl_kX792Lo method=GET status=500 client_ip=172.19.0.1 error="Can't download source image: The image request timed out"
/app/imagedata/download.go:245 github.com/imgproxy/imgproxy/v3/imagedata.download
/app/imagedata/image_data.go:134 github.com/imgproxy/imgproxy/v3/imagedata.Download
/app/processing_handler.go:306 main.handleProcessing.func2
/app/processing_handler.go:293 main.handleProcessing
/app/server.go:113 main.withCORS.func1
/app/server.go:164 main.withPanicHandler.func1
/app/router/router.go:102 github.com/imgproxy/imgproxy/v3/router.(*Router).ServeHTTP
/usr/local/go/src/net/http/server.go:2937 net/http.serverHandler.ServeHTTP
/usr/local/go/src/net/http/server.go:1996 net/http.(*conn).serve
/usr/local/go/src/runtime/asm_amd64.s:1599 runtime.goexit
```

What's strange on this is that imgproxy stops all other requests as well, needs manual intervention (restart) as the health-check in this case is still returing 200 OK - despite the fact, that something seems to be broken.

What can we do in that case? Increase Concurrency?

Version is the latest 3.14

**Comment by Klaitos** [comment] 2023-03-18 08:53
On our side, we mitigated the issue by doing in the liveness probe a fetch on a static image in the same source bucket. In that case, when the timeout occurs, its also occurs on the healthcheck route.

**Comment by DarthSim** [comment] 2023-03-23 13:24
I made some tweaks to the source image downloading process in the `latest` build. Also, if you use many different image sources, I'd recommend setting `IMGPROXY_CLIENT_KEEP_ALIVE_TIMEOUT` to 0.

**Comment by shakalandy** [comment] 2023-03-23 19:12
> I made some tweaks to the source image downloading process in the `latest` build. Also, if you use many different image sources, I'd recommend setting `IMGPROXY_CLIENT_KEEP_ALIVE_TIMEOUT` to 0.

Thanks! 
Will try it out once there is a new release with the improvements.

**Comment by y3ti** [comment] 2023-03-31 10:31
I have similar issue. In my case, I have 2-4 image sources. Every 1-2 days image downloading process sticks and the imgproxy can't download new images using existing TCP connection. 

If I kill existing sockets / TCP connections, then the imgproxy establishes new connections and it magically start working. Here is the command I use:

```sh
# standalone imgproxy
$ sudo ss -t -o 'dport = :443' -K
```

```
# docker container
$ docker run -it --net container:<imgproxy-container-name-or-id> --privileged nicolaka/netshoot ss -t -o 'dport = :443' -K
```

@DarthSim May I ask when new imgproxy version will be released? I would like to test your latest commit: https://github.com/imgproxy/imgproxy/commit/24f4d43a0f874f87321c897899ac88ec6c66e87b

**Comment by DarthSim** [comment] 2023-04-10 17:42
The `v3.15.0` release includes my tweaks. Hope this will solve the problem

**Comment by y3ti** [comment] 2023-04-13 09:47
Unfortunately, the new version (`v3.15.0`) doesn't solve this issue (in my case) :( I will try to collect more details about the issue.

**Comment by y3ti** [comment] 2023-04-13 13:51
I experimented with `IMGPROXY_CLIENT_KEEP_ALIVE_TIMEOUT=0` on `v3.14.0`, it didn't work for me. This was likely because I had a small number of image sources, meaning that the TCP connection was always open (~1 req/sec to the same DNS domain)

**Comment by DarthSim** [comment] 2023-04-13 17:27
I guess I finally found what may cause this issue. HTTP/2 connections may become stuck, and Go's HTTP client doesn't handle this properly by default and tries to reuse stuck connections. Since GCS uses HTTP/2, this bug affects it too. more info: https://github.com/golang/go/issues/30702, https://github.com/googleapis/google-cloud-go/issues/3522

I'll try to reproduce the bug with stuck connections and add a walkaround. The temporary solution is to disable HTTP/2 globally: `GODEBUG=http2client=0`

**Comment by DarthSim** [comment] 2023-04-13 20:23
The `latest` build includes the fix. I'll try to make a release tomorrow.

**Comment by DarthSim** [comment] 2023-04-18 17:00
> I'll try to make a release tomorrow

Don't make promises you're not ready to keep 😅

Anyway, the `v3.16.0` release is out, and it includes the fix for this issue. I configured the HTTP clients so they check HTTP/2 connections' liveness. This allows imgproxy to successfully recover after an HTTP/2 connection becomes stuck. Also, I made imgroxy to repeat requests for source images after getting a "connection lost" error.

**Comment by Klaitos** [comment] 2023-04-19 07:34
Many thanks @DarthSim for not giving up on this issue. We will try this release today.

**Comment by shakalandy** [comment] 2023-04-19 07:56
Deployed as well over here and testing already, thanks!

**Comment by shakalandy** [comment] 2023-04-24 18:33
Working like a charm - no new incident toll now, thanks!! 🎉

**Comment by y3ti** [comment] 2023-04-26 07:07
It works! @DarthSim thank you very very much! :)

**Comment by Klaitos** [comment] 2023-04-26 07:45
Talking for @renchap and I, the issue seems to be resolved on our side too. I guess we can close the issue, congratz @DarthSim

**Comment by DarthSim** [comment] 2023-04-26 15:56
Ah, thank goodness! Thanks everyone for the info! Closing the issue

**Closed by DarthSim** 2023-04-26 15:56 UTC

**Comment by chendo** [comment] 2024-04-26 04:55
We're still saw this issue in v3.22.0 Pro, where eventually an instance of `imgproxy` gets into a state where all source requests time out after 10s.

We were able to resolve the issue by setting `IMGPROXY_CLIENT_KEEP_ALIVE_TIMEOUT` to `0`, even though we only hit the one source host.
