### ISSUE TITLE
Ability to output image "as is"

### ISSUE THREAD

**Issue by windstep** [imgproxy/imgproxy#449] opened 2020-07-28 13:23 UTC
Hey!

In our project we are using animated gifs in some places. Are there any ways to just output them "as is"? We have two main troubles: heavy image processing and infinitely looped gifs are stopping after 3 loops (I think, MAX_ANIMATED_FRAMES affects this). I think, in some cases, we should add ability to ignore sizes of every image, so the imgproxy acts like cdn.

**Comment by DarthSim** [comment] 2020-07-30 12:26
Hey! It looks like a duplicate of #393. However, I'd like to take a look at problematic GIFs.

**Closed** 2020-11-20 05:46 UTC
