### ISSUE TITLE
Transformation to add white space around image

### ISSUE THREAD

**Issue by timuric** [imgproxy/imgproxy#355] opened 2020-03-04 12:46 UTC
I am looking for a way to add white space around image crop as illustrated in the image bellow. Anyone has ideas how to achieve that with the existing transformations? 

![image](https://user-images.githubusercontent.com/4006792/75546698-73222d00-5a29-11ea-9ead-f85dda4766b4.png)

**Comment by a1tus** [comment] 2020-03-05 17:32
At the moment we are trying to use imgproxy for our project. We've improved trim function for our needs (will send PR soon) and now I try to add "padding" option.

On input we have bg color and image size. The problem is that I don't quite understand how to initialize empty image properly after `imgWithPadding := new(vipsImage)`. If someone could help me with that I would show our branch with this option.

**Comment by a1tus** [comment] 2020-03-06 19:31
It turned out in easier code than I expected: https://github.com/imgproxy/imgproxy/pull/358
It still need some checks for edge cases but works well in our test environment.

**Comment by DarthSim** [comment] 2020-04-09 10:06
Closed by #358. Thanks to @a1tus

**Closed by DarthSim** 2020-04-09 10:06 UTC
