### ISSUE TITLE
HEIC images raises an error Dimensions data wan't found in meta box

### ISSUE THREAD

**Issue by jpalumickas** [imgproxy/imgproxy#346] opened 2020-02-24 10:28 UTC
Hey!

HEIC images raise an error `Dimensions data wan't found in meta box`. I'm using format jpg in params. The image was taken with iPhone X. Also, I found that if I choose other HEIC images also, they raise the same error.

**Comment by jpalumickas** [comment] 2020-02-25 22:22
Maybe some information that might be helpful:
1. libheif needs libde265 dependency https://github.com/libvips/libvips/issues/1511#issuecomment-572886098 to correctly read and convert to jpg files. So maybe `libde265-dev` needs to be added to dependencies. Also, maybe `libx265-dev` should be added too for converting to HEIC images https://github.com/libvips/libvips/issues/1511#issuecomment-573483782.
2. I saw that with older version libheif HEIC images don't respect orientation. I tested new libheif version (1.6.2) and it supports correct orientation. I saw that imgproxy using libheif-dev from Debian buster, I think there is 1.3.0 version, so maybe it's need to be updated to latest.

**Comment by DarthSim** [comment] 2020-02-26 11:43
Could you give me a sample? My samples don’t cause this error.

**Comment by jpalumickas** [comment] 2020-02-27 08:58
Hey @DarthSim !

Attached few samples that not working 🙂 

[Not working.zip](https://github.com/imgproxy/imgproxy/files/4260521/Not.working.zip)

**Comment by DarthSim** [comment] 2020-02-27 09:02
Hey Justas,
Thanks a lot, I'll take a look!

**Comment by DarthSim** [comment] 2020-02-27 11:46
Sorry, I can't reproduce the issue. Both samples work fine with both the latest and v2.10.0 docker images.

The `Dimensions data wasn't found in meta box` error may occur when imgproxy tries to extract the image dimensions but ones are not found in the `meta` box. libheif is not involved at this stage. The code that does that wasn't changed significantly since it was originally written. So now I'm pretty puzzled why it doesn't work on your side.

**Comment by jpalumickas** [comment] 2020-02-27 11:47
@DarthSim we're using Heroku for imgproxy, maybe this can cause an issue?

**Comment by DarthSim** [comment] 2020-02-27 11:49
Since you're using a Docker image, it shouldn't. Which version of imgproxy are you running?

**Comment by jpalumickas** [comment] 2020-02-27 11:50
@DarthSim we're using latest from master (with ICO fix)

**Comment by jpalumickas** [comment] 2020-02-27 11:58
@DarthSim Also we use these params when requesting HEIC image
```
width: 600 , height: 600 , format: 'jpg'
```

Also, we use S3 with Imgproxy, and these settings (but I don't think they are related to this problem)
IMGPROXY_TTL: 259200
IMGPROXY_MAX_SRC_RESOLUTION: 60
IMGPROXY_SALT, IMGPROXY_KEY and IMGPROXY_SECRET

**Comment by DarthSim** [comment] 2020-02-27 12:00
Sorry, I'm out of ideas :( https://imgproxy-test-darthsim.herokuapp.com/unsafe/rs:fit:600:600/plain/http://img.darthsim.me/XGpXInDVCF.HEIC@jpg

**Comment by jpalumickas** [comment] 2020-02-27 12:02
Also we use `imgproxy.rb` (master branch) and we use `config.base64_encode_urls = true`

**Comment by DarthSim** [comment] 2020-02-27 12:14
This shouldn't affect, but I tried anyway https://imgproxy-test-darthsim.herokuapp.com/unsafe/s:600:600/aHR0cDovL2ltZy5k/YXJ0aHNpbS5tZS9Y/R3BYSW5EVkNGLkhF/SUM.jpg

Could you give me your imgproxy URL that processes one of that "broken" images? Maybe I'll find something there. Feel free to email me if you don't want to share it here.

**Comment by jpalumickas** [comment] 2020-02-27 12:54
@DarthSim  ok I found that if I try to load that image from local:// it works, but if I load from s3:// I get that error

**Comment by jpalumickas** [comment] 2020-02-27 13:00
@DarthSim also when I comment out these lines:
```
if !d.IsFilled() {
  return errors.New("Dimensions data wan't found in meta box")
}
```
it still works, so maybe the problem is with checking dimensions when loading from s3? 🤔 

Also, when I tested I see that some images does not have the correct orientation, but as I mentioned this before, this is due the old libheif version, maybe it's possible to install the latest version?

**Comment by DarthSim** [comment] 2020-03-17 10:04
@jpalumickas Sorry for the huge delay.

The image source shouldn't affect dimensions checking. I've tried to serve your sample from S3, and it works just ok: https://imgproxy-test-darthsim.herokuapp.com/unsafe/resize:fit:1000:1000/sh:0/plain/s3://img.darthsim.me/XGpXInDVCF.HEIC.

The only thing that comes to my mind is that the image from `local://` and the image from `s3://` are two different images.

> maybe it's possible to install the latest version?

v2.11.0 and the latest images contain the latest libheif built from source.

**Comment by jpalumickas** [comment] 2020-03-17 16:01
Hey!

We updated Imgproxy to master and we have still same problem. `Dimensions data wasn't found in meta box` 
>The image source shouldn't affect dimensions checking

We thought that too, but we checked with the same image in local and s3 sources.
Also, what is different for us, that we're wasabi.com (but they have same S3 API so I don't think it's a problem, because other images are working fine). 

Also we're using ActiveStorage and it saving images without extension on S3, only hash. Example: `s3://bucket/00smc164if112xtxnfxegaj9bva5` Can this be a problem?

**Comment by jkoehl** [comment] 2020-05-29 13:46
We are seeing the same issue. We happen to also store our images in S3 without extensions. Perhaps there is something to that.

**Comment by jkoehl** [comment] 2020-06-23 01:03
I noticed that the HEIC image that works is landscape and one that we have that does not work is a portrait image. It seems like iOS device images in portrait would have orientation flags on them. That supports the theory above related to orientation.

Could be related to this recent fix in upstream library https://github.com/libvips/libvips/pull/1680

**Comment by jeroenvdheuvel** [comment] 2020-07-09 09:02
@DarthSim I'm having the same issue as well. I'm able to reproduce it on your test instance: https://imgproxy-test-darthsim.herokuapp.com/unsafe/rs:fit:600:600/plain/https://s3-eu-west-1.amazonaws.com/static-sr.s3.werkspot.nl/e83087b4-9a1d-4d15-b820-220b772c2f51.heic@jpg

Locally (and it looks like your instance as well) imgproxy crashes after trying it multiple times.

This image works fine and I'm able to crop it via vipsthumbnail.

This image doesn't work for me with imgproxy via http, s3 and local storage.

**Comment by DarthSim** [comment] 2020-07-09 11:37
Thanks a bunch! i finally managed to reproduce the bug using your sample

**Comment by DarthSim** [comment] 2020-07-10 09:51
@jeroenvdheuvel Thanks again! I found a bug and fixed it in master (`latest` image): https://imgproxy-test-darthsim.herokuapp.com/unsafe/rs:fit:600:600/plain/https://s3-eu-west-1.amazonaws.com/static-sr.s3.werkspot.nl/e83087b4-9a1d-4d15-b820-220b772c2f51.heic@jpg

@jpalumickas @jkoehl should be fixed for you too

**Comment by jpalumickas** [comment] 2020-07-10 10:14
@DarthSim thanks for fixing this 🙂 

I deployed latest master to Heroku now and we get this error now:
```
2020-07-10T10:10:54.761523+00:00 app[web.1]: ERROR   [2020-07-10T10:10:54Z] Completed in 3.102833135s /vu8b96T0Wo3qPXpp6yhqgq77YCUfmz9EOlxBdUo9dGo/s:600:600/czM6Ly92aWV0YS1z/dGFnaW5nL21tYnk5/NnU3ZjJ0bjRycGI4/eGsyOG5sY24wZ2s.jpg  request_id=6893be3f-4a97-4f66-b859-e7c4e5f6266c method=GET status=500
error="heifload_buffer: bad image dimensions on decode\n"
2020-07-10T10:10:54.761531+00:00 app[web.1]: /app/vips.go:500 main.(*vipsImage).CopyMemory
2020-07-10T10:10:54.761531+00:00 app[web.1]: /app/process.go:391 main.transformImage
2020-07-10T10:10:54.761531+00:00 app[web.1]: /app/process.go:758 main.processImage
2020-07-10T10:10:54.761532+00:00 app[web.1]: /app/processing_handler.go:189 main.handleProcessing
2020-07-10T10:10:54.761532+00:00 app[web.1]: /app/server.go:97 main.withSecret.func1
2020-07-10T10:10:54.761533+00:00 app[web.1]: /app/server.go:85 main.withCORS.func1
2020-07-10T10:10:54.761533+00:00 app[web.1]: /app/router.go:100 main.(*router).ServeHTTP
2020-07-10T10:10:54.761534+00:00 app[web.1]: /usr/local/go/src/net/http/server.go:2808 net/http.serverHandler.ServeHTTP
2020-07-10T10:10:54.761534+00:00 app[web.1]: /usr/local/go/src/net/http/server.go:1896 net/http.(*conn).serve
2020-07-10T10:10:54.761535+00:00 app[web.1]: /usr/local/go/src/runtime/asm_amd64.s:1374 runtime.goexit
```

Maybe it's not related to this one?

**Comment by DarthSim** [comment] 2020-07-10 10:23
It's a libheif bug :( https://github.com/strukturag/libheif/issues/211.

**Comment by jpalumickas** [comment] 2020-07-10 10:27
oh, thanks @DarthSim

**Comment by jeroenvdheuvel** [comment] 2020-07-13 08:19
Thanks @DarthSim for picking it up so fast!

**Comment by DarthSim** [comment] 2020-07-13 12:39
@jeroenvdheuvel It will be soon. I'm preparing a release.

**Comment by DarthSim** [comment] 2020-07-17 14:13
`v2.14.0` is released

**Closed by DarthSim** 2020-07-17 14:13 UTC

**Comment by kvf77** [comment] 2020-07-27 15:36
We keep repeating this error on the latest version.

Completed in 1.077445103s /lOn-LOvIIF3k50PTTYPjeg6XAcrvJgC8N8bs27kr2XI/fit/600/600/sm/0/bG9jYWw6Ly8vMDAwLzAwMC8wMDMvMzE4OS5oZWlj.jpg  request_id=UQvFTErlAmlbXMYWurqKl method=GET status=500 error="heifload_buffer: bad image dimensions on decode\n"
/app/vips.go:576 main.(*vipsImage).CopyMemory
/app/process.go:391 main.transformImage
/app/process.go:758 main.processImage
/app/processing_handler.go:189 main.handleProcessing
/app/server.go:85 main.withCORS.func1
/app/router.go:100 main.(*router).ServeHTTP
/usr/local/go/src/net/http/server.go:2808 net/http.serverHandler.ServeHTTP
/usr/local/go/src/net/http/server.go:1896 net/http.(*conn).serve
/usr/local/go/src/runtime/asm_amd64.s:1374 runtime.goexit

**Comment by windstep** [comment] 2020-07-28 05:42
@DarthSim in addition, we are using latest version of darthsim/imgproxy container `docker exec container imgproxy version` outputs 2.14.1.

**Comment by DarthSim** [comment] 2020-07-28 08:43
"bad image dimensions on decode" is a libheif bug

**Comment by windstep** [comment] 2020-07-28 09:05
Are there any ways to fix it right now? At least any working walkaround?

**Comment by DarthSim** [comment] 2020-07-28 11:19
I don't see any workarounds here. libheif needs to be fixed, but I don't have enough expertise to fix it.

**Comment by daneren2005** [comment] 2020-08-05 23:17
We just updated from ImgProxy 2.8.2 to 2.14.1 and are getting the same error `heifload_buffer: bad image dimensions on decode` on most HEIC files I have tried.  That libheif issue has been closed with no intention on fixing it.  Is it possible we can revert back to an older verison of libheif without this issue?  Obviously if libheif was upgraded to fix another issue we can't.  I tried 5 sample HEIC files I had on hand and 3 of them were broken, so not a good track record there...


PS here is an example image from a user's phone that is broken:
![IMG_2412](https://user-images.githubusercontent.com/414653/89473083-df226300-d736-11ea-99ce-a4554468fb83.jpg)

**Comment by DarthSim** [comment] 2020-08-06 06:13
John made a workaround for this issue: https://github.com/libvips/libvips/pull/1756. Let’s wait for Vips 8.10

**Comment by daneren2005** [comment] 2020-08-06 14:43
Sounds good to me

**Comment by jpalumickas** [comment] 2020-08-11 08:26
@DarthSim libvips v8.10.0 was released 🎉

**Comment by DarthSim** [comment] 2020-08-11 12:06
That's great! I'm preparing the release.
