### ISSUE TITLE
Trim surrounding white-space / background 

### ISSUE THREAD

**Issue by jeepey** [imgproxy/imgproxy#265] opened 2019-11-19 11:26 UTC
Hi,

We're a happy user of imgproxy for a few months already. We're currently investigating how we can automatically trim the surrounding white-space around images in our product catalog. There are quite a few libraries available which we could implement, but it would be much better if this would be done with a transformation in our existing image resizer. 

Is this a feature you would consider for imgproxy? 
Example use-case is similar to this:
https://stackoverflow.com/questions/36446678/best-way-to-remove-borders-crop-image

Thanks!

**Comment by DarthSim** [comment] 2020-01-28 10:19
The latest build has `trim` processing option: https://docs.imgproxy.net/#/generating_the_url_advanced?id=trim

**Comment by DarthSim** [comment] 2020-02-14 10:38
The feature was released in v2.9.0

**Closed by DarthSim** 2020-02-14 10:38 UTC
Labels: feature request

**Comment by a1tus** [comment] 2020-02-29 07:42
Can you please help mу to understand, it seems like vips lib accepts also background color that needs to be trimmed: https://github.com/libvips/libvips/issues/670 - but imgproxy don't. Is it by design?

And one more thing, if I also need to make this trim to cut only equal parts from sides (I mean if it is about to cut 5px from left and 10px from right then it would choose min value and cut 5px from both sides) - my only option to fork or may be it can be useful in general?

**Comment by a1tus** [comment] 2020-03-06 19:27
For those, who may be interested, I've created PR with some trim improvements: https://github.com/imgproxy/imgproxy/pull/357
