### ISSUE TITLE
Imgproxy generated webp won't render in Safari

### ISSUE THREAD

**Issue by pbright** [imgproxy/imgproxy#624] opened 2021-04-27 03:39 UTC
Given an imgproxy instance built from source on Ubuntu 20.04.2:
http://143.198.59.117/media/thumbs/

With the following environment variables:
IMGPROXY_LOCAL_FILESYSTEM_ROOT=/path/to/media
IMGPROXY_ENABLE_WEBP_DETECTION=true

And the following source image:
http://143.198.59.117/media/test.jpg

I have an issue where some jpgs are converted to webp by imgproxy but not rendered by Safari (Version 14.0.3, Mac OS Big Sur):
http://143.198.59.117

The issue is rare in that it only occurs with a small number of jpgs, and only at specific sizes, but will consistently occur when those conditions are met. 

The generated webp loads correctly in Chrome and Firefox at all sizes. It will render successfully in Safari if you change the dimensions in the imgproxy url to 50/50, for example.

Note that visiting the imgproxy url directly will result in the image being rendered correctly, but I believe that is a red herring as it seems Safari doesn't send the accept header when loading directly to an image, and the generated image is therefore a jpg.

It's quite possible this is an error with libvips rather than imgproxy but I've never used libvips directly so not sure where to go from here.

Any help would be much appreciated.

**Comment by DarthSim** [comment] 2021-04-27 11:22
Hey!

That is very weird behavior of Safari. Especially considering that most of the images work correctly. It looks like Safari can't display some images if they don't have XMP data (some images without XMP work fine though). I'll keep digging into it, but as a temporary solution, I'd recommend you disable `IMGPROXY_STRIP_METADATA` to keep XMP data.

**Comment by DarthSim** [comment] 2021-04-27 12:01
Yup, it's confirmed Safari bug: https://bugs.webkit.org/show_bug.cgi?id=219977.

Closing the issue as it doesn't look like it's possible to fix this without keeping XMP, and
1. I'm not sure this will fix the issue completely.
2. Keeping XMP as is with `IMGPROXY_STRIP_METADATA` enabled is not an option.

**Closed by DarthSim** 2021-04-27 12:01 UTC

**Comment by pbright** [comment] 2021-04-27 22:55
Thanks Sergey, really appreciate your time looking into this.

Just to confirm that disabling IMGPROXY_STRIP_METADATA was a partial fix, some images now render correctly but a handful still don't, as you suspected might be case. I'm dealing with a large image set and the number of images with issues is very low, so disabling IMGPROXY_STRIP_METADATA might be an acceptable workaround for others.
